steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          --build-arg DATABASE_URL=$$DATABASE_URL \
          --build-arg CERTIFICATE_URL=$$CERTIFICATE_URL \
          -f searcher/Dockerfile \
          -t gcr.io/$PROJECT_ID/minshumi-search:$COMMIT_SHA \
          .
    secretEnv: ["DATABASE_URL", "CERTIFICATE_URL"]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/minshumi-search:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "minshumi-search"
      - "--image"
      - "gcr.io/$PROJECT_ID/minshumi-search:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--service-account=minshumi-search-prod-service"
      - --set-secrets
      - GCS_BUCKET=searcher-gcs-bucket:latest,DATABASE_URL=cockroach-db-prod-url:latest
images:
  - "gcr.io/$PROJECT_ID/minshumi-search:$COMMIT_SHA"
availableSecrets:
  secretManager:
    - versionName: projects/megane-s-gcp/secrets/searcher-gcs-bucket/versions/latest
      env: GCS_BUCKET
    - versionName: projects/megane-s-gcp/secrets/cockroach-db-prod-url/versions/latest
      env: DATABASE_URL
    - versionName: projects/megane-s-gcp/secrets/searcher-certificate-url/versions/latest
      env: CERTIFICATE_URL
