steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          --build-arg DATABASE_URL=$$DATABASE_URL \
          --build-arg CERTIFICATE_URL=$$CERTIFICATE_URL \
          --build-arg ART_LIST_LIMIT=50000 \
          --progress=plain \
          -f scheduled_recommend/Dockerfile \
          -t gcr.io/$PROJECT_ID/minshumi-notification:$COMMIT_SHA \
          .
    secretEnv: ["DATABASE_URL", "CERTIFICATE_URL"]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/minshumi-notification:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "minshumi-notification"
      - "--image"
      - "gcr.io/$PROJECT_ID/minshumi-notification:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--service-account=minshumi-search-prod-service"
      - "--set-secrets"
      - "DATABASE_URL=searcher-database-url:latest,CERTIFICATE_URL=searcher-certificate-url:latest"
      - "--task-timeout=60m"
      - "--memory=4Gi"
images:
  - "gcr.io/$PROJECT_ID/minshumi-notification:$COMMIT_SHA"
availableSecrets:
  secretManager:
    - versionName: projects/megane-s-gcp/secrets/searcher-database-url/versions/latest
      env: DATABASE_URL
    - versionName: projects/megane-s-gcp/secrets/searcher-certificate-url/versions/latest
      env: CERTIFICATE_URL
options:
  diskSizeGb: "2"
